version: "3.8"

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - COMMANDLINE_ARGS=--listen --enable-insecure-extension-access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./models:/stable-diffusion-webui/models
      - ./outputs:/stable-diffusion-webui/outputs
      - ./extensions:/stable-diffusion-webui/extensions
